# control parameters for 'metropolis'
# ------------------------------------
a=   2        # eOut   : output control (1: final result, 2: each step, 3: more information    default:    2)
n=   1        # nTstPar: number of parameter sets tested in one step                          (default:    1)
c=   1        # eConstr: defines constraints (0: no constr., 1: P_j,min < P_j < P_j,max        default:    1)
s=2500        # mSteps : max. number of optimization steps                                    (default: 2500)
o=  10        # nStpOut: each 'nStpOut' step is written to the output                         (default:   10)
d= 100        # nStpMin: each 'nStpMin' step the actual minimum is written                    (default:  100)
g=   1.0      # Sigma  : standard deviation of a measurement value                            (default:    1.0)
r=   0.995    # Qverm  : maximal ratio of chi square new : chi square old for best set        (default:    0.995)
m=   1.0E-24  # Qmin   : minimal error square sum - fit terminated                            (default:    1.0E-24)
l=   0.0      # Qlimit : error square sum that determines border of local minimum to be noted (default:    0.0)
