# control parameters for 'fit_grad_mc'
# ------------------------------------
a= 2      # eOut  :  control parameter for output (1: only final result, 2: fit parameters after each step, 3: additionally some function values)
s=25      # mSteps:  max. number of optimization steps                          (default: 25)
n=10      # mDamps:  max. number of dampings                                    (default: 10)
d=0.5     # Damp  :  damping factor (reduction of t )                           (default:  0.5)
t=0.5     # Tfac  :  fraction Q-reduction in original and linearized fct.       (default:  0.5)
r=0.999   # Qverm :  ratio of Q-reduction within 1 step that stops fitting      (default:  0.999)
m=1.0E-24 # Qmin  :  Q-value to stop fitting                                    (default:  1.0E-24)
