Optimisation of the sample position    # name of the optimization
#
opt_grad_mc   #  algorithm           existing: 'opt_grad_mc', 'metropolis', 'opt_grad', 'swarm'
sim_opt_pc    #  application option  existing: 'sim_opt_pc', 'sim_opt_grid' (used for MC simulations), 'fit_pc' (to be used for fitting)
fom           #  program to calculate figure of merit (will be maximized)
none          #  cluster option 'none' for no option, '--node=long' (SGE) or '--slpartition=long' (SLURM) for long queue 
#
# parameters
#  start    min     max   delta     description
1    2.0   -10.0    10.0   0.05    # P1: hor. shift       [cm]
2    2.0   -10.0    10.0   0.05    # P2: vert. shift      [cm]
  

