# ---------------------------------------------------------------------------------------------
STD           # directory of VITESS executables             STD: directory from 'std_instr.cmd
STD           # simulation directory (during optimization)  STD: directory from 'std_instr.cmd
# ---------------------------------------------------------------------------------------------
sample.mtl    # files to be copied for 'FigureOfMerit'
STD           # defines function to transfer optimization parameters to simulation parameters         
# ---------------------------------------------------------------------------------------------
# SimPar            FitPar
  6 -y        # S1 = P1:   hor. shift     [cm]  
  6 -z        # S2 = P2:   vert. shift    [cm] 
# ---------------------------------------------------------------------------------------------
 