# ------------------------------------------------------------------------------------------------
STD                # directory of VITESS executables       STD: directory from 'std_instr.cmd
STD                # parameter directory of the simulation STD: directory from 'std_instr.cmd
# ------------------------------------------------------------------------------------------------
sample.mtl         # files to be copied for 'FigureOfMerit'
# ------------------------------------------------------------------------------------------------
STD                # defines function to transfer optimization parameters to simulation parameters         
# SimPar  FitPar    ------------------------------------------------------------------------------
  6 -y             # P(1)   hor. shift     [cm]  
  6 -z             # P(2)   vert. shift    [cm] 
# ------------------------------------------------------------------------------------------------
 