# control parameters for 'swarm'
# ------------------------------------
b= 10     # nBees: number of swarm individuals (bees)                    (default:  10   , max: 300 )
s= 150    # nSteps: max. number of optimization steps                    (default:  150  )
f= 10     # nFinish: max. number of opt. steps without improvement       (default:  10   )    
w= 0.4    # w0_min: min. weight inertia term                             (default:  0.4  )
W= 0.9    # w0_max: max. weight inertia term                             (default:  0.9  )
u= 0.5    # w1_min: min. weight local best                               (default:  0.5  )
U= 2.5    # w1_max: max. weight local best                               (default:  2.5  )
v= 0.5    # w2_min: min. weight global best                              (default:  0.5  )
V= 2.5    # w2_max: max. weight global best                              (default:  2.5  )
x= 1      # eOut: Output level 1 = basic, 2 = evolution file, 3 = DEBUG  (default:  1    )
