sample_environment:
  executable: "sample_environment"
  label: "sample_environment"
  parameters:
  - name: "sParFile"
    type: "file"
    plottable: false
    label: "parameter file"
    tooltip: "File containing parameters of the sample environment These parameters are only used if they are not given as direct input parameters."
    prefix: "-F"
  - name: "sStructFile"
    type: "file"
    plottable: false
    label: "structure factor file"
    tooltip: "This file describes the material of the sample environment. It contains the d-spacing value and information to calculate the scattering cross-section of each reflection. It can be in .str (VITESS), .laz and .lau format."
    prefix: "-s"
  - name: "eDirInOut"
    type: "int"
    label: "direction"
    tooltip: "Direction of the beam passing the sample environment 1=in: sample environment before sample, 2=out: sample environment after sample"
    column: 0
    prefix: "-r"
  - name: "iColor"
    type: "int"
    label: "colour"
    tooltip: "Colour of the neutrons coherently scattered from the environment, incoherently scattered neutrons get 'color+1'"
    min: 0
    column: 0
    prefix: "-c"

  - name: "PosMainX"
    type: "float"
    label: "X [cm]"
    tooltip: "Center position X of the sample environment  (usually the sample position)"
    default: 30.0
    column: 0
    prefix: "-x"
  - name: "PosMainY"
    type: "float"
    label: "Y [cm]"
    tooltip: "Center position Y of the sample environment (usually the sample position)"
    column: 1
    prefix: "-y"
  - name: "PosMainZ"
    type: "float"
    label: "Z [cm]"
    tooltip: "center position Z of the sample environment (usually the sample position)"
    default: 0.0
    column: 2
    prefix: "-z"

  - name: "Thickness"
    type: "float"
    label: "thickness [cm]"
    tooltip: "Thickness of the sample environment, which is assumed to be a hollow cylinder."
    min: 0.0001
    default: 0.5
    column: 0
    prefix: "-t"
  - name: "Diameter"
    type: "float"
    label: "diameter [cm]"
    tooltip: "Outer diameter of the sample environment, which is assumed to be a hollow cylinder."
    default: 15.0
    min: 0.0001
    column: 1
    prefix: "-d"
  - name: "Height"
    type: "float"
    label: "height [cm]"
    tooltip: "Outer height of the sample environment, which is assumed to be a hollow cylinder."
    default: 20.0
    min: 0.0001
    column: 2
    prefix: "-h"

  - name: "Title"
    type: "title"
    label: "Scattering"
  - name: "MuScatIncoh"
    type: "float"
    label: "incoherent scattering [1/cm]"
    tooltip: "Macroscopic incoherent scattering cross section of the sample environment material. If a non-zero value is given, incoherent scattering is applied."
    default: 0.0
    min: 0.0
    column: 0
    prefix: "-i"
  - name: "MuScatTotal"
    type: "float"
    label: "total scattering [1/cm]"
    tooltip: "Macroscopic total scattering cross section of the sample environment material (used for attenuation)"
    default: 0.1
    min: 0.0
    column: 1
    prefix: "-T"
  - name: "MuAbsorb"
    type: "float"
    label: "absorption [1/cm]"
    tooltip: "Macroscopic absorption cross section of the sample environment material  (used for attenuation)"
    default: 0.0
    min: 0.0
    column: 2
    prefix: "-m"
  - name: "UCV"
    type: "float"
    label: "unit cell volume [A^3]"
    tooltip: "Unit cell volume of the sample environment material"
    default: 65.0
    min: 0.0001
    column: 0
    prefix: "-U"
