/********************************************************************************************/
/*  VITESS module 'sample_ncrystal.c'                                                       */
/*                                                                                          */
/* The free non-commercial use of these routines is granted                                 */
/* providing due credit is given to the authors.                                            */
/* 1.0  Dec 2024  N. Violini     scattering pattern generated by NCrystal                   */
/********************************************************************************************/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "convert.h"
#include "general.h"
#include "init.h"
#include "softabort.h"
#include "matrix.h"
#include "intersection.h"
#include "sample.h"
#include "NCrystal/ncrystal.h"

#define  STRING_BUFFER 50


/******************************/
/** Prototypes               **/
/******************************/
void   OwnInit(int argc, char *argv[]);                       // Reads input parameters and sets global variables
void   OwnCleanup();                                          // Does module specific cleanup
void   ReadFile(char* sFileName);                             // Reads input file for ncrystal
void   CalcAndWritePar(SampleType *pSample);                  // Calculates arrays from input parameters and writes to log file
void   SetGeometry(const char* sColor);                       // Fills the structure stGeometry for visualization
void   OutputTransform(VectorType Pos, VectorType Dir);       // Co-ordinate transformation to output frame
void   spin_flip(VectorType Spin);                            // Spin flip handler
long S_q_w_ncrystal(double *wl, double *prob, VectorType Dir); // calculates S of Q, omega leveraging the ncrystal database
/* Ncrystal specific */
int get_physical_state(ncrystal_info_t);                               // gets the physical state of the sample
void ncrystal_message_handler(const char *message, unsigned msg_class); // handles error messages

/******************************/
/** Global Variables         **/
/******************************/

/*  Variables from the GUI input */
char      *pSmplFileName=NULL;         //      -f        [-]   pointer to the name of the ncrystal sample file
double     Temp=0.0;                   //      -T        [K]  temperature of the sample
long       Repetition=1;               //      -A        [-]   repetitions (how many trajectories to generate per incoming trajectory)
VtSmplGeom eGeom=VT_NO_GEOM;           //      -G        [-]   geometry parameter: "cylinder" "hollow-cylinder" "sphere" "rectangular"
VectorType PosSample={0.0,0.0,0.0},    //      -X -Y -Z  [cm]  center position of the sample
           TranslOut={0.0,0.0,0.0};    //      -x -y -z  [cm]  center position of the output frame
double     AnglSmplHor =0.0,           //      -o       [rad]  horizontal angle of the sample orientation, relative to standard orientation
           AnglSmplVert=0.0,           //      -O       [rad]  vertical angle of the sample orientation, relative to standard orientation
           Diameter = 0.0,             //      -t        [cm]  thickness or diameter of the sample
           Height   = 0.0,             //      -h        [cm]  height of the sample
           Width    = 0.0,             //      -w        [cm]  width of the sample
           AnglOutHor =0.0,            //      -u       [rad]  horizontal angle of the output frame, relative to input orientation
           AnglOutVert=0.0;            //      -U       [rad]  vertical angle of the output frame, relative to input orientation
long   eGeom_id = 0;                                // -G  0=default; 1=cyl ;2=holcyl; 3=ball; 4=cub

/* Variables from the GUI input: Ncrystal variables */
double d_cutoff=0.0,                   // -d  [Angstroms]   Minimum d-spacing (in Å) to consider in the simulation.
       Dist=0.0,                       // -D   [cm]    distance of (the center of) the module from entry point of the component
       mos=0.0,                        // -m  [number]    Crystal mosaicity
       LmbdInit=0.0,                   // -M [Angstroms] Reference wavelenght for incident neutron wavevector calculation
       h_dir1=0.0,                       // -h [number]  Miller index h defining dir1 for ncrystal
       k_dir1=0.0,                       // -k [number]  Miller index k defining dir1 for ncrystal
       l_dir1=0.0,                       // -l [number]  Miller index l defining dir1 for ncrystal
       x_dir1=0.0,                       // -a [number]  Component x of the unit vector defining dir1 in the ncrystal lab
       y_dir1=0.0,                       // -b [number]  Component y of the unit vector defining dir1 in the ncrystal lab
       z_dir1=0.0,                       // -c [number]  Component z of the unit vector defining dir1 in the ncrystal lab
       h_dir2=0.0,                      // -H [number]  Miller index h defining dir2 for ncrystal
       k_dir2=0.0,                      // -K [number]  Miller index k defining dir2 for ncrystal
       l_dir2=0.0,                      // -L [number]  Miller index l defining dir2 for ncrystal
       x_dir2=0.0,                      // -A [number]  Component x of the unit vector defining dir2 in the ncrystal lab
       y_dir2=0.0,                      // -B [number]  Component y of the unit vector defining dir2 in the ncrystal lab
       z_dir2=0.0;                      // -C [number]  Component z of the unit vector defining dir2 in the ncrystal lab

/* Variables determined from input parameters or trajectory data */
SampleType stSample;                   //                      sample geometry
VectorType DimSample   ={0.0,0.0,0.0}, //                      size of the sample
           DimSampleHol={0.0,0.0,0.0}, //                      array to use 'IntersectsWithCylinder()' for hollow cylinders
           k_reference ={0.0,0.0,0.0}; //                      initial k-vector
double     ProbCutoff=0.0;             //                      neutron weight, below which the trajectory is removed
double     RotMatrixSample [3][3],     //                      rotation matrix to transfer to coordinate system of the sample
           RotMatrixOut    [3][3],     //                      rotation matrix to transfer to the output coordinate system
           RotMatrixNCrystal[3][3];    //                      rotation matrix to transfer into coordinate system of NCrystal
int        n_flipped = 0,              //                      number of neutrons being flipped in incoherent scattering
           n_non_flipped = 0,          //                      number of neutrons not being flipped in incoherent scattering
           n_coh = 0,                  //                      number of neutrons being scattered in coherent scattering
           no_hit=0;                   //                      number of neutrons not hitting the sample

/* Variables specifying sample properties */
double     AbsorptionC = 0.0,          // calculated    [barns] Absorption cross section
           ScatteringT = 0.0,          // calculated    [barns] Total scattering cross section
           ScatteringI = 0.0,          // calculated    [barns] Incoherent scattering cross section
           ScatteringC = 0.0,          // calculated    [barns] Coherent scattering cross section of the sample
           mu_abs = 1.0,               // calculated    [1/cm] Linear absorption coefficient
           mu_sca = 1.0,               // calculated    [1/cm] Total linear scattering coefficient
           mu_sci = 1.0,               // calculated    [1/cm] Incoherent linear scattering coefficient
           mu_scc = 1.0,               // calculated    [1/cm] Coherent linear scattering cross coefficient
           dirtol = 0.0057;            //               [deg]  Tolerance on dir axis n.2 of the sample
int        state_of_matter = 0;        // read from Ncrystal info: 0 = unknown, 1 = solid, 2 = gas, 3 = liquid

VtFrameGen eFrame=VT_FRAME_USER;       //                [-]   flag: user defined output frame

/* Ncrystal specific or related variables */
ncrystal_scatter_t material={NULL};       // scattering material definition
ncrystal_process_t proc_coh={NULL};       // coherent scattering process definition
char configString[1012];                            // Buffer to hold the full config string
double dir_fin[3]= {0.0,0.0,0.0};       // Neutron direction after scattering process
double  ekin = 0.0,                                 // incident neutron energy calculated from its wavelength
        xsect = 0.0,                                // neutron cross section calculated by ncrystal
        wl_fin = 0.0;                               // final neutron energy calculated from its wavelength
int i_loop = 0;                                     // integer used to filter the first 10 scattering events

/* Declare RNG for NCrystal */
double my_randgen(void);


/******************************/
/** Main Program             **/
/******************************/
int main(int argc, char **argv)
{
  Neutron     InNeutron, OutNeutron;
  long       repet=0,   i=0;
  double     TOF=0.0,   WL=0.0, Prob=0.0,
             PathLength   =0.0, PathLengthHol   =0.0;

  double tmp_rand = 0.0, sf_probability = 0.0;

  // flag used to distinguish between coherent and incoherent S(Q,omega)
  int inc_flag;
  VectorType Pos1f ={0.0,0.0,0.0}, Pos2f=  {0.0,0.0,0.0}, Pos3f={0.0,0.0,0.0}, Pos4f={0.0,0.0,0.0},
             Pos1v ={0.0,0.0,0.0}, Pos2v=  {0.0,0.0,0.0}, Pos3v={0.0,0.0,0.0}, Pos4v={0.0,0.0,0.0},
             propag={0.0,0.0,0.0}, propag1={0.0,0.0,0.0},                              // propagation vectors e.g. from entry to point of scattering to calculate TOF
             Pos   ={0.0,0.0,0.0}, Dir=    {0.0,0.0,0.0}, Pos_final={0.0,0.0,0.0},
             SpinVector;

  ncrystal_setrandgen(my_randgen);  // Set the vitess RNG as the random generator for NCrystal

  /* Set the custom message handler for ncrystal */
  ncrystal_setmsghandler(ncrystal_message_handler);
  ncrystal_sethaltonerror(0);       // Disable halting on error
  ncrystal_setquietonerror(1);      // Suppress default error messages

  // initialisation
  // --------------
  InitNeutron(&OutNeutron);
  InitNeutron(&InNeutron);
  InitVector(SpinVector);

  _eModule = MCN_SMPL_NCRYSTAL;

  Init(argc,argv, _eModule);
  PrintModuleName(_eModule, "1.0");
  OwnInit(argc, argv);

  bVisInstalled = TRUE;
  if (bVisInstr)
    bBlowUp     = TRUE;

  /* Determines the dependent parameters and write out important parameters */
  CalcAndWritePar(&stSample);

  DECLARE_ABORT

  // Loop over all trajectories
  // --------------------------
  while (ReadNeutrons() != 0)
  {
    for (i=0; i<NumNeutGot; i++)
    {
      CHECK;
      // Only write out event if EOB line is found, otherwise process trajectory
      if (IsEOB(&(InputNeutrons[i]))==TRUE)
      {
        WriteNeutron(&(InputNeutrons[i]));
      }
      else
      {
        PathLengthHol = 0.0;
        NormVectorX(InputNeutrons[i].Vector);
        CopyNeutron(&InputNeutrons[i], &InNeutron);

        /* reads the incident neutron spin as a vector */
        CopyVector(InputNeutrons[i].Spin, SpinVector);

        /* initialises the incoherent flag to default */
        inc_flag=0;

        /* translates and rotates into frame of the sample  */
        SubVector(InputNeutrons[i].Position, PosSample) ;
        RotVector(RotMatrixSample, InputNeutrons[i].Position) ;
        RotVector(RotMatrixSample, InputNeutrons[i].Vector) ;

        /* gives intersection positions with sample */
        if (eGeom==VT_CYL)
        {
          if (IntersectionWithCylinder(DimSample, InputNeutrons[i].Position, InputNeutrons[i].Vector, Pos1f, Pos2f) == 0){
          no_hit = no_hit+1;
          goto getlost ;
          }
        }

        if (eGeom==VT_HOL_CYL)
        {
          if (IntersectionWithCylinder(DimSample, InputNeutrons[i].Position, InputNeutrons[i].Vector, Pos1f, Pos4f) == 0)
          {
            no_hit = no_hit+1;
            goto getlost ;
          }
          else
          {
            if (IntersectionWithCylinder(DimSampleHol, InputNeutrons[i].Position, InputNeutrons[i].Vector, Pos2f, Pos3f) == 0)
              CopyVector(Pos4f, Pos2f);
            if (IntersectionWithCylinder(DimSampleHol, InputNeutrons[i].Position, InputNeutrons[i].Vector, Pos2f, Pos3f) == 1)
            {  double r=MonteCarlo(-1.,1);

              if ((CompareVectors(Pos1f, Pos2f)==1)&&(CompareVectors(Pos3f, Pos4f)==1)) goto getlost;

              if ((CompareVectors(Pos1f, Pos2f)==0)&&(CompareVectors(Pos3f, Pos4f)==0))
              {
                if(r>0.)
                {
                  SubVector(Pos2f, Pos1f);
                  PathLengthHol = LengthVector(Pos2f);
                  CopyVector(Pos3f, Pos1f); CopyVector(Pos4f, Pos2f);
                }
                else
                {
                  SubVector(Pos4f, Pos3f);
                  PathLengthHol = 0.;
                }
              }
              if ((CompareVectors(Pos1f, Pos2f)==0)&&(CompareVectors(Pos3f, Pos4f)==1))
              {
                PathLengthHol = 0.;
              }
              if((CompareVectors(Pos1f, Pos2f)==1)&&(CompareVectors(Pos3f, Pos4f)==0))
              {
                CopyVector(Pos3f, Pos1f); CopyVector(Pos4f, Pos2f);
                PathLengthHol = 0.;
              }
            }
          }
        }


        if (eGeom==VT_CUBE)
        {
          if(IntersectionWithRectangular(DimSample, InputNeutrons[i].Position, InputNeutrons[i].Vector, Pos1f, Pos2f) == 0){
            no_hit = no_hit+1;
            goto getlost ;
          }
        }

        if (eGeom==VT_SPHERE)
        {
          if(IntersectionWithSphere(DimSample, InputNeutrons[i].Position, InputNeutrons[i].Vector, Pos1f, Pos2f) == 0) {
            no_hit = no_hit+1;
            goto getlost ;
          }
        }

        for (repet=0;repet<Repetition;repet++)
        {/**/

          CHECK;
          CopyVector(Pos1f, Pos1v) ;
          CopyVector(Pos2f, Pos2v) ;
          CopyVector(Pos3f, Pos3v) ;
          CopyVector(Pos4f, Pos4v) ;

          TOF  = InputNeutrons[i].Time ;
          WL   = InputNeutrons[i].Wavelength ;
          Prob = InputNeutrons[i].Probability ;

          CopyVector(InputNeutrons[i].Position, Pos) ;
          CopyVector(InputNeutrons[i].Vector, Dir) ;

          /* scattering position and TOF until scattering */
          SubVector(Pos2v, Pos1v);                                 // Pos2v: vector from entry to exit of the path through the sample
          MultiplyByScalar(Pos2v, MonteCarlo(0.,1.));      // Pos2v now vector from entry into sample to point of scattering
          PathLength = LengthVector(Pos2v) + PathLengthHol;
          AddVector(Pos1v, Pos2v);                                 // Pos1v now vector to point of scattering

          CopyVector(Pos1v, propag);
          SubVector(propag, Pos);
          TOF += LengthVector(propag) / V_FROM_LAMBDA(WL) ;

          CopyVector(Pos1v, Pos) ;            /*scattering position */

          /* attenuation untill scattering normalized to maximal path */
          Prob *= (double)(1.- exp(-PathLength * mu_abs * WL - PathLength * mu_sca) );

          //fprintf(LogFilePtr, " Inside the repetition loop 2. \n");

          /* point of scattering for trajectory visualization */
          if (bVisTraj==TRUE)
          {
            Neutron ScatNeut;
            CopyNeutron(&InputNeutrons[i], &ScatNeut);
            CopyVector (Pos1v, ScatNeut.Position);
            ScatNeut.Probability=Prob;

            WriteScatIAP(&ScatNeut, VT_SCATTERED, RotMatrixSample, PosSample);
          }

          //fprintf(LogFilePtr, " Inside the repetition loop 3. \n");

          // decides if incoherent scattering or not */
          tmp_rand = MonteCarlo(0.,1.);
          if (tmp_rand < ScatteringI/ScatteringT)
          {
            inc_flag=1;
            // flip spin of incoherent scattering with probability 2/3 */
            sf_probability = MonteCarlo(0.,1.);
            if (sf_probability < 2.0/3.0)
            {
              spin_flip(SpinVector);
              n_flipped ++;
            }
            else
            {
              n_non_flipped ++;
            }
            /* attenuation due to incoherent scattering cross section */
            Prob *= (double) (1. - exp(- PathLength * mu_sci) ) ;
          }
          //* attenuation due to coherent scattering cross section */
          else
          {
            Prob *= (double) (1. - exp(- PathLength * mu_scc) );
            n_coh ++;
          }
          //fprintf(LogFilePtr, " Inside the repetition loop 4. \n");
          /* S(q,w) scattering: new neutron variables*/
          Prob *= WL ;
          if (inc_flag == 0) {
            if (S_q_w_ncrystal(&WL, &Prob, Dir) == 0) goto getlost2 ;
          }
          if (inc_flag == 1) Prob *= ScatteringI;
          Prob *= 1/WL ;

          CHECK;

          /* attenuation succeeding scattering */
          if (eGeom==VT_CYL)
          {
            if(IntersectionWithCylinder(DimSample, Pos, Dir, Pos1v, Pos2v) == 0)
              goto getlost2 ;
          }

          if (eGeom==VT_HOL_CYL)
          {

            if (IntersectionWithCylinder(DimSample, Pos, Dir, Pos1v, Pos4v) == 0)
            {
              goto getlost2;
            }
            else
            {
              if (IntersectionWithCylinder(DimSampleHol, Pos, Dir, Pos2v, Pos3v) == 0)
              {
                CopyVector(Pos4v, Pos2v);
              }
              else
              {
                VectorType Propag;
                CopyVector(Pos2v, Propag);
                SubVector(Propag, Pos);

                if (CompareVectors(Pos3v, Pos4v)==0)
                {
                  if (ScalarProduct(Propag, Dir) > 0.)
                  {
                    CopyVector(Pos4v, propag1);
                    SubVector(propag1, Pos3v);
                    PathLengthHol = LengthVector(propag1);
                  }
                  else
                  {
                    PathLengthHol = 0.;
                    CopyVector(Pos3v, Pos1v); CopyVector(Pos4v, Pos2v);
                  }
                }
                else
                {
                  PathLengthHol = 0.;
                }
              }
            }
          }

          if (eGeom==VT_CUBE)
          {
            if(IntersectionWithRectangular(DimSample, Pos, Dir, Pos1v, Pos2v) == 0) goto getlost2 ;
          }
          if (eGeom==VT_SPHERE)
          {
            if(IntersectionWithSphere(DimSample, Pos, Dir, Pos1v, Pos2v) == 0) goto getlost2 ;
          }

          /* path in the sample after scattering */
          CopyVector(Pos2v, Pos_final) ;
          SubVector(Pos_final, Pos) ;
          PathLength = LengthVector(Pos_final) + PathLengthHol ;

          if (PathLengthHol != 0.)
            CopyVector(Pos4v, Pos2v);  /* for hollow cylinder option: set output position to where it crosses the outer cylinder if crossed  */

          Prob *= exp(-PathLength * AbsorptionC * WL - PathLength * ScatteringT);

          /* Output matters */
          CopyVector(Pos2v, propag);
          SubVector(propag, Pos);
          TOF += LengthVector(propag) / V_FROM_LAMBDA(WL) ;

          OutputTransform(Pos2v, Dir) ;

          if (Prob <= ProbCutoff)
            goto getlost2 ;

          /* transmit coordinates which were not changed, the rest overwrite below */
          CopyNeutron( &InputNeutrons[i], &OutNeutron );
          OutNeutron.Time = TOF ;
          OutNeutron.Wavelength = WL ;
          OutNeutron.Probability = Prob/Repetition ;

          CopyVector(Pos2v, OutNeutron.Position) ;
          CopyVector(dir_fin, OutNeutron.Vector) ;
          CopyVector(SpinVector, OutNeutron.Spin);

          /* writes output binary file */
          WriteNeutron(&OutNeutron);

        getlost2: ;
        }/*repetition*/
        continue;

        /* here continues if neutron gets lost */
      getlost:
        WriteDIAP(&InNeutron, VT_OUTSIDE, PosSample[0] - InNeutron.Position[0]);
      }
    }
  }

  // Finish: write log, geometry and instrument file, free memory
  // ------------------------------------------------------------
  fprintf(LogFilePtr, " Number of spin-flipped neutrons in incoherent scattering        : %d \n", n_flipped);
  fprintf(LogFilePtr, " Number of non-spin-flipped neutrons in incoherent scattering    : %d \n", n_non_flipped);
  fprintf(LogFilePtr, " Number of neutrons in coherent scattering    : %d \n", n_coh);
  fprintf(LogFilePtr, " Number of neutrons that didn't hit the sample: %d \n", no_hit);

  my_exit:
  /* write geometry file */
  //char* geom = strdup("white");
  //SetGeometry(geom);
  //free(geom);
  SetGeometry("white");

  /* Do module specific cleanups */
  OwnCleanup();

 /* Do the general cleanup */
  Cleanup(TranslOut[0], TranslOut[1], TranslOut[2], AnglOutHor, AnglOutVert);

  return 0;
}


/*******************************************************/
/** Own initialization of the sample_inelast module   **/
/*******************************************************/
void OwnInit(int argc, char *argv[])
{
  int i;
  InitRotMatrix(RotMatrixSample);
  InitRotMatrix(RotMatrixOut);
  InitRotMatrix(RotMatrixNCrystal);

  ProbCutoff=wei_min ;

  /* Scan all command line parameters */
  //  abcdefghijklmnopqrstuvwxyz
  //  abcd fgh  klm o   stu wxyz
  //  ABCD  GH  KLM O  RSTU WXYZ
  for (i=1; i<argc; i++)
  {
    if (argv[i][0]!='+')
    {
      switch (argv[i][1])
      {
        case 'f':
          pSmplFileName = &argv[i][2];
          break;
        case 'T':
          sscanf(&argv[i][2], "%lf", &Temp) ;
          break;
        case 'd':
          sscanf(&argv[i][2], "%lf", &d_cutoff) ;
          break;
        case 'm':
          sscanf(&argv[i][2], "%lf", &mos) ;
          break;
        case 's':
          sscanf(&argv[i][2], "%d", &state_of_matter) ;
          break;
        case 'D':
          sscanf(&argv[i][2], "%lf", &dirtol) ;
          break;
        case 'R':
          sscanf(&argv[i][2], "%ld", &Repetition) ;
          break;

        /* sample shape, position, size and orientation */
        case 'G':
          eGeom_id = atol(&argv[i][2]);
          break;
        case 'X':
          sscanf(&argv[i][2], "%lf", &PosSample[0]);
          break;
        case 'Y':
          sscanf(&argv[i][2], "%lf", &PosSample[1]);
          break;
        case 'Z':
          sscanf(&argv[i][2], "%lf", &PosSample[2]);
          break;
        case 't':
          sscanf(&argv[i][2], "%lf", &Diameter);
          break;
        case 'g':
          sscanf(&argv[i][2], "%lf", &Height);
          break;
        case 'w':
          sscanf(&argv[i][2], "%lf", &Width);
          break;
        case 'o':
          sscanf(&argv[i][2], "%lf", &AnglSmplHor);
          break;
        case 'O':
          sscanf(&argv[i][2], "%lf", &AnglSmplVert);
          break;

        /* Neutron wavelength */
        case 'M':
          sscanf(&argv[i][2], "%lf", &LmbdInit) ;
          break;

        case 'h':
        case 'k':
        case 'l':
        case 'a':
        case 'b':
        case 'c':
        case 'H':
        case 'K':
        case 'L':
        case 'A':
        case 'B':
        case 'C':
          if (state_of_matter == 1){
            switch (argv[i][1]){
              case 'h':
                          sscanf(&argv[i][2], "%lf", &h_dir1);
                          break;
              case 'k':
                          sscanf(&argv[i][2], "%lf", &k_dir1);
                          break;
              case 'l':
                          sscanf(&argv[i][2], "%lf", &l_dir1);
                          break;
              case 'a':
                          sscanf(&argv[i][2], "%lf", &x_dir1);
                          break;
              case 'b':
                          sscanf(&argv[i][2], "%lf", &y_dir1);
                          break;
              case 'c':
                          sscanf(&argv[i][2], "%lf", &z_dir1);
                          break;
              case 'H':
                          sscanf(&argv[i][2], "%lf", &h_dir2);
                          break;
              case 'K':
                          sscanf(&argv[i][2], "%lf", &k_dir2);
                          break;
              case 'L':
                          sscanf(&argv[i][2], "%lf", &l_dir2);
                          break;
              case 'A':
                          sscanf(&argv[i][2], "%lf", &x_dir2);
                          break;
              case 'B':
                          sscanf(&argv[i][2], "%lf", &y_dir2);
                          break;
              case 'C':
                          sscanf(&argv[i][2], "%lf", &z_dir2);
                          break;
            }
          }
          break;

        /* Output frame */
        case 'x':
          sscanf(&argv[i][2], "%lf", &TranslOut[0]);
          break;
        case 'y':
          sscanf(&argv[i][2], "%lf", &TranslOut[1]);
          break;
        case 'z':
          sscanf(&argv[i][2], "%lf", &TranslOut[2]);
          break;
        case 'u':
          sscanf(&argv[i][2], "%lf", &AnglOutHor);
          break;
        case 'U':
          sscanf(&argv[i][2], "%lf", &AnglOutVert);
          break;

        default:
          fprintf(LogFilePtr,"ERROR: unkown command option: %s\n",argv[i]);
          exit(-1);
      }
    }
  }

  if (pSmplFileName==NULL)
    Error("Parameter file name missing") ;

  if(Repetition == 0)
    Error("Repetition rate must be > 0 ");

  return;

}/* End OwnInit */


/*******************************************************/
/** Does module specific cleanup                      **/
/*******************************************************/
void OwnCleanup()
{
  if (material.internal != NULL) ncrystal_unref(&material);
  return;
}


/**********************************************************************/
/** calculates ariables from input parameters and writes to log file **/
/**********************************************************************/
void  CalcAndWritePar(SampleType* pSample)
{
  char   sFrm[30]="";
  double dir[3]={0.0,0.0,0.0};
  VectorType  DirSample={0.0,0.0,0.0}; // sample orientation

  //  ncrystal specific variables
  unsigned atomdata_index = 0;
  double fraction=0;
  const char *label = NULL, *description= NULL;
  double mass = 0.0, inc_xs =0.0, coh_sl=0.0, coh_xs=0.0, abs_xs=0.0;
  unsigned z=0, a=0, n_sub_components=0;
  double density = 0.0;
  double number_density = 0.0;
  unsigned n_components = 0;
  unsigned i = 0;
  ncrystal_atomdata_t atom_data={NULL};
  ncrystal_info_t info={NULL};
  char fallback_label[50]="";
  const char *errmsg = NULL;
  const char *errtype = NULL;
  int ret = 0;

  switch (eGeom_id) //1:cyl 2:holcyl 3:ball 4:cub
    { case 1    :   {eGeom = VT_CYL;break;}
      case 2    :   {eGeom = VT_HOL_CYL; DirSample[2]=1.0; break;}
      case 3    :   {eGeom = VT_SPHERE ;                   break;}
      case 4    :   {eGeom = VT_CUBE   ; DirSample[0]=1.0; break;}
      default        : Error("Sample geometry missing");
    }

  // sets sample dimension and orientation and checks if a valid geometry is given
  switch (eGeom)
  { case VT_CYL    :
    case VT_HOL_CYL: DirSample[2]=1.0; break;
    case VT_SPHERE :                   break;
    case VT_CUBE   : DirSample[0]=1.0; break;
    default        : Error("Sample geometry missing");
  }

  if (eGeom==VT_HOL_CYL)
  {
    DimSample[0] = Diameter;  DimSampleHol[0] = Width;
    DimSample[1] = 0.0;       DimSampleHol[1] = 0.0;
    DimSample[2] = Height;    DimSampleHol[2] = Height;
  }
  else
  {
    DimSample[0] = Diameter;
    DimSample[1] = Width;
    DimSample[2] = Height;
  }

  /* converts degs in radian etc. */
    AnglSmplHor  *= M_PI/180. ;
    AnglSmplVert *= M_PI/180. ;
    AnglOutHor   *= M_PI/180. ;
    AnglOutVert  *= M_PI/180. ;

  if (PosSample[0] < 0.5*DimSample[0] || PosSample[0] < 0.5*DimSample[1] || PosSample[0] < 0.5*DimSample[2])
    Error("Distance to sample smaller than half the sample size in at least one dimension");

  FrameGen_ID2Txt(sFrm, eFrame);
  fprintf(LogFilePtr, "%s:\n", sFrm);
  fprintf(LogFilePtr, "  output position (X',Y',Z'): %9.4f %9.4f %9.4f cm \n",     TranslOut[0], TranslOut[1], TranslOut[2]);
  fprintf(LogFilePtr, "  output angles   (hor,vert): %9.4f %9.4f           deg\n", Degrees(AnglOutHor), Degrees(AnglOutVert));

  FillRotMatrixZY(RotMatrixSample,  AnglSmplVert, AnglSmplHor) ;
  FillRotMatrixZY(RotMatrixOut,     AnglOutVert,  AnglOutHor) ;
  FillRotMatrixY(RotMatrixNCrystal, -M_PI/2) ;

  // fills data structures
  RotBackVector(RotMatrixSample, DirSample);

  InitSample(pSample);
  FillSample(pSample, eGeom, PosSample[0], PosSample[1], PosSample[2],  DirSample[0], DirSample[1], DirSample[2], Diameter, Height, Width, 0.0);

  fprintf(LogFilePtr, "  offset angles (h,v) : %9.4f %9.4f           deg\n", Degrees(AnglSmplHor), Degrees(AnglSmplVert));

  fprintf(LogFilePtr,"repetition         : %ld\n", Repetition) ;
  if(Repetition > 1) fprintf(LogFilePtr,"\nWarning: Excessive use of repetition rate > 1 can lead to wrong results. Be sure that you have very good statistics\n"
                                        "\nin wavelength, time, x,y,z and directions just before the sample\n") ;

  /* Validate sample file name */
  if (!pSmplFileName || !*pSmplFileName) {
      fprintf(LogFilePtr, "File name is invalid or empty!\n");
      //exit(-1);
      return;
  }

  /* Construct the configuration string */
  if (state_of_matter == 1){
    ret = snprintf(configString, sizeof(configString),
                    "%s;temp=%.1fK;dcutoff=%.1f;mos=%.1fdeg;dir1=@crys_hkl:%d,%d,%d@lab:%.3f,%.3f,%.3f;dir2=@crys_hkl:%d,%d,%d@lab:%.3f,%.3f,%.3f;dirtol=%.4fdeg",
                    pSmplFileName, Temp, d_cutoff, mos, (int)h_dir1, (int)k_dir1, (int)l_dir1, x_dir1, y_dir1, z_dir1, (int)h_dir2, (int)k_dir2, (int)l_dir2, x_dir2, y_dir2, z_dir2, dirtol);
  }
  else {
    ret = snprintf(configString, sizeof(configString),"%s", pSmplFileName);
  }

  /* Check for string truncation or formatting errors */
  if (ret < 0 || ret >= (int)sizeof(configString)) {
      fprintf(LogFilePtr, "Error: Configuration string formatting failed or was truncated.\n");
      //exit(-1);
      return;
  }

  fprintf(LogFilePtr, "Generated Config String: %s\n", configString);

  /* Create NCrystal scatter handle */
  material = ncrystal_create_scatter(configString);
  fprintf(LogFilePtr, "Checking material handle after creation...\n");
  if (!ncrystal_valid(material.internal)) {
      fprintf(LogFilePtr, "Material handle is invalid.\n");
      if (ncrystal_error()) {
          // Fetch and log the error message
          errmsg = ncrystal_lasterror();
          errtype = ncrystal_lasterrortype();
          fprintf(LogFilePtr, "Error creating NCrystal scatter handle for config string:\n%s\n", configString);
          fprintf(LogFilePtr, "Error Type: %s\nError Message: %s\n", errtype ? errtype : "Unknown", errmsg ? errmsg : "No message");
          ncrystal_clearerror(); // Clear the error state
          Error("Vitess simulation ends here. Please check!");
      } else {
          fprintf(LogFilePtr, "Unknown error creating scatter handle for config string:\n%s\n", configString);
      }
      if (material.internal != NULL) ncrystal_unref(&material);
      exit(-1);
  } else {
      fprintf(LogFilePtr, "NCrystal processing setup successful.\n\n");
  }

  fprintf(LogFilePtr,"For calculations of attenuation and coherent/incoherent scattering, the following data will be used:\n\n");
  info = ncrystal_create_info(configString);
  if(info.internal != NULL) {
    int state_of_matter_read = get_physical_state(info);
    if(state_of_matter_read == 0){
      Error("State of matter unknown. Please check!\n");
    }
    if (state_of_matter_read == 1 && state_of_matter != 1){
      Error("State of matter from the input field is 'not-solid', while NCrystal material info returns 'solid'. Please check!\n");
    }
    if (state_of_matter_read == 2 && state_of_matter == 1){
      Error("State of matter from the input field is 'solid', while NCrystal material info returns 'gas'. Please check!\n");
    }
    if (state_of_matter_read == 3 && state_of_matter == 1){
      Error("State of matter from the input field is 'solid', while NCrystal material info returns 'liquid'. Please check!\n");
    }
    number_density = ncrystal_info_getnumberdensity(info);
    fprintf(LogFilePtr,"Number density of the compound       : %9.4f [1/Ang^3].\n", number_density);
  }

  // Access density information
  density = ncrystal_info_getdensity(info);
  fprintf(LogFilePtr,"Material Density: %f g/cm³\n", density);

  // Access composition information
  n_components = ncrystal_info_ncomponents(info);
  fprintf(LogFilePtr,"Number of Components: %u\n", n_components);

  for (i = 0; i < n_components; ++i) {
      fprintf(LogFilePtr, "Processing component %u...\n", i);

      // Get component info
      ncrystal_info_getcomponent(info, i, &atomdata_index, &fraction);
      fprintf(LogFilePtr, "  Component %u: atomdata_index=%d, fraction=%f\n", i, atomdata_index, fraction);

      // Validate fraction
      if (fraction < 0.0 || fraction > 1.0) {
          fprintf(LogFilePtr, "  Warning: Invalid fraction (%f) for component %u. Skipping.\n", fraction, i);
          continue;
      }

      // Create component atom data
      atom_data = ncrystal_create_component_atomdata(info, i);
      fprintf(LogFilePtr, "  Created atom_data for component %u: internal=%p\n", i, (void*)atom_data.internal);

      // Validate atom_data
      if (!ncrystal_valid(atom_data.internal)) {
          fprintf(LogFilePtr, "  Error: atom_data is invalid for component %u. Skipping.\n", i);
          continue;
      }

      // Get fields from atom_data
      ncrystal_atomdata_getfields(atom_data, &label, &description, &mass, &inc_xs, &coh_sl, &abs_xs, &n_sub_components, &z, &a);

      // Log intermediate field values
      fprintf(LogFilePtr, "  Fields for component %u:\n", i);
      fprintf(LogFilePtr, "    Label: %s\n", label ? label : "NULL");
      fprintf(LogFilePtr, "    Description: %s\n", description ? description : "NULL");
      fprintf(LogFilePtr, "    Mass: %f amu\n", mass);
      fprintf(LogFilePtr, "    Incoherent x-sect: %f barns\n", inc_xs);
      fprintf(LogFilePtr, "    Coherent Scattering Length: %f fm\n", coh_sl);
      fprintf(LogFilePtr, "    Absorption x-sect: %f barns\n", abs_xs);
      fprintf(LogFilePtr, "    Z: %u, A: %u\n", z, a);
      fprintf(LogFilePtr, "    Number of Sub-components: %u\n", n_sub_components);

      // Handle missing label
      if (!label || label[0] == '\0') {
          fprintf(LogFilePtr, "  Warning: Label is empty for component %u.\n", i);

          if (z > 0) {
              if (a > 0) {
                  snprintf(fallback_label, sizeof(fallback_label), "Z=%u, A=%u", z, a);
              } else {
                  snprintf(fallback_label, sizeof(fallback_label), "Z=%u (natural isotopic mix)", z);
              }
              fallback_label[sizeof(fallback_label) - 1] = '\0'; // Ensure null termination
              label = fallback_label;
              fprintf(LogFilePtr, "  Fallback Label: %s\n", fallback_label);
          } else {
              label = "Unknown";
              fprintf(LogFilePtr, "  Assigned default label: Unknown\n");
          }
      }

      // Calculate coherent cross-section
      coh_xs = 4 * M_PI * pow(coh_sl * 1e-15, 2) * 1e28;
      fprintf(LogFilePtr, "  Coherent x-sect calculated: %f barns\n", coh_xs);

      // Print element details
      fprintf(LogFilePtr, "  Element: %s\n", description ? description : (label ? label : "Unknown"));

      // Update global totals
      ScatteringC += fraction * coh_xs;
      ScatteringI += fraction * inc_xs;
      AbsorptionC += fraction * abs_xs;

      // Release atom data safely
      if (ncrystal_valid(atom_data.internal)) {
          fprintf(LogFilePtr, "  Releasing atom_data for component %u.\n", i);
          ncrystal_unref(&atom_data);
      }
  }

  // Release the material info
  if (info.internal != NULL) ncrystal_unref(&info);

  dir[0]=h_dir1;
  dir[1]=k_dir1;
  dir[2]=l_dir1;

    /* calculates coherent scattering cross section as ScatteringC = ScatteringT - ScatteringI */
  mu_sci = number_density * ScatteringI ;
  mu_scc = number_density * ScatteringC ;
  mu_sca = mu_sci+mu_scc;
  mu_abs = number_density * AbsorptionC ;

  fprintf(LogFilePtr, "\nScattering parameters\n\n");

  fprintf(LogFilePtr,"TOTAL Coherent scattering x-sect %.2f [barn]\n",ScatteringC);
  fprintf(LogFilePtr,"TOTAL Incoherent scattering x-sect %.2f [barn]\n",ScatteringI);
  ScatteringT = ScatteringI + ScatteringC;
  fprintf(LogFilePtr,"TOTAL scattering x-sect %.2f [barn]\n\n",ScatteringT);

  fprintf(LogFilePtr, "\nThese are the first 10 scattering events:\n");
}


/*******************************************************/
/** Reads data from input file                        **/
/*******************************************************/
void ReadFile(char* sFileName)
{
  // opens input file (program exit in case of error)
  FILE* pFile = OpenInputFile2(sFileName, "file content", "r");
  //FILE *pFile = fopen(sFileName, "r");

  if (pFile!=NULL)
  {
    fprintf(LogFilePtr, "Succesfully opened NCrystal library file: %s\n",sFileName);
    fclose(pFile);
  }
  else fprintf(LogFilePtr, "WARNING: Cannot open sample file %s\n",sFileName);
}

/*******************************************************/
/** Fills the structure stGeometry for visualization  **/
/*******************************************************/
void SetGeometry(const char* sColor)
{
  /* Geometry data */
  if (bVisInstr)
  {
    sprintf(sVisDescrpt, "%s:%s", sModuleName, sColor);
    //snprintf(sVisDescrpt, sizeof(sVisDescrpt), "%s:%s", sModuleName, sColor);
    stGeometry.pDescr  =  sVisDescrpt;
    stGeometry.eModule = _eModule;

    SetSampleGeometry(&stSample, 0.0);
  }
}


/*******************************************************/
/** Co-ordinate transformation to output frame        **/
/*******************************************************/
void OutputTransform(VectorType Pos, VectorType Dir)
{
  /* computes neutron variables in the initial frame */
  RotBackVector(RotMatrixSample, Pos) ;
  RotBackVector(RotMatrixSample, Dir) ;
  AddVector(Pos, PosSample) ;

  /* computes neutron variables in the output frame */
  SubVector(Pos, TranslOut) ;
  RotVector(RotMatrixOut, Pos) ;
  RotVector(RotMatrixOut, Dir) ;


} /* End OutputTransform()*/


/*******************************************************/
/** S(q,w) scattering: new neutron variables          **/
/*******************************************************/

long S_q_w_ncrystal(double *wl, double *prob, VectorType Dir)
{
  double ekin, ekin_fin, xsect, delta_ekin = 0.0;

  i_loop = i_loop + 1;

  if(*wl == 0.0) return 0;

  ekin = ncrystal_wl2ekin(*wl);
  proc_coh = ncrystal_cast_scat2proc(material);

  if (!ncrystal_valid(proc_coh.internal)) {
    fprintf(LogFilePtr, "NCrystal process handle is invalid for scatter object.\n");
    ncrystal_unref(material.internal);
    return 0;
  }

  // rotates to the NCrystal coordinate refence system
  RotVector(RotMatrixNCrystal, Dir);
  ncrystal_crosssection(proc_coh, ekin, (const double (*)[3]) Dir, &xsect);
  ncrystal_samplescatter(material, ekin, (const double (*)[3]) Dir, &ekin_fin, &dir_fin);

  if(ekin_fin){
    wl_fin = ncrystal_ekin2wl (ekin_fin);
    delta_ekin = ekin - ekin_fin;
  }

  if (i_loop < 10){
   fprintf(LogFilePtr, "Scattering at energy transfer %f [meV] in direction (%f, %f, %f) gives scattering cross-section %f [barns].\n",
      delta_ekin*1e3, dir_fin[0], dir_fin[1], dir_fin[2], xsect);
  }

  // rotates back to Vitess coordinate refence system
  RotBackVector(RotMatrixNCrystal, dir_fin);

  //exp(-PathLength * mu_abs * WL - PathLength * mu_sci) ;
  *prob *= xsect ;

  return 1 ;
}

/*******************************************************/
/** Spin flip function                                **/
/*******************************************************/
void spin_flip(VectorType Spin)
{
  // spin flipping function
  if ( Spin[0] != 0) Spin[0] = - Spin[0];
  if ( Spin[1] != 0) Spin[1] = - Spin[1];
  if ( Spin[2] != 0) Spin[2] = - Spin[2];
}


int get_physical_state(ncrystal_info_t info) {
    // Get state of matter
    int state = 0;
    unsigned spacegroup = 0;
    double a=0.0, b=0.0, c=0.0, alpha=0.0, beta=0.0, gamma=0.0, volume=0.0;
    unsigned n_atoms=0;

    state = ncrystal_info_getstateofmatter(info);

    switch (state) {
        case 0:
            fprintf(LogFilePtr,"State of matter: Unknown\n");
            break;
        case 1:
            fprintf(LogFilePtr,"State of matter: Solid\n");
            // Further refine solid state:

            if (ncrystal_info_getstructure(info, &spacegroup, &a, &b, &c, &alpha, &beta, &gamma, &volume, &n_atoms)) {
                fprintf(LogFilePtr,"Solid type: Crystal (space group: %u)\n", spacegroup);
            } else {
                fprintf(LogFilePtr,"Solid type: Polycrystal or Powder\n");
            }
            break;
        case 2:
            fprintf(LogFilePtr,"State of matter: Gas\n");
            break;
        case 3:
            fprintf(LogFilePtr,"State of matter: Liquid\n");
            break;
        default:
            fprintf(LogFilePtr,"State of matter: Undefined\n");
            break;
    }
    return state;
}

void ncrystal_message_handler(const char *message, unsigned msg_class) {
    if (msg_class == 1) {
        fprintf(LogFilePtr, "Warning: %s\n", message);
    } else if (msg_class == 0) {
        fprintf(LogFilePtr, "Info: %s\n", message);
    } else {
        fprintf(LogFilePtr, "Raw Output: %s\n", message);
    }
}

double my_randgen(void) {
  return Vran();
}
